# -*- coding: utf-8 -*-
"""codeninja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFMoY8OhF95KX7GJ-rACr93Xg527fNFn
"""

##Given N , find sum of all even numbers less than N. 
N = int(input('Enter number N: '))
sum=0
for number in range(1, N+1):
    if(number % 2 == 0):
        print("{0}".format(number))
        sum = sum + number

print("The Sum of Even Numbers from 1 to {} = {}".format(number, sum))

##Given three values - Start Fahrenheit Value (S), End Fahrenheit value (E) and Step Size (W), you need to convert all Fahrenheit values from Start to End at the gap of W, into their corresponding Celsius values and print the table.
##Input Format :
##3 integers - S, E and W respectively
from os import *
from sys import *
from collections import *
from math import *

def conv_temp(sf, ef, w):
    # Implement Your Code Here
    while True:
        celcius = 0
        if sf <= ef:
            celcius = (sf - 32) * 5 / 9
            print("temp in fahr is {} , temp in celcius is {}".format(sf, celcius))
            sf = sf + w

        else:
            break

sf = int(input())
ef = int(input())
step = int(input())
conv_temp(sf, ef, step)



##Input and integer N and print the sum of all its even numbers and odd numbers seperately 

number = input("Enter a number:")
b=list(map(int,number))
print(b)

even = 0
odd = 0
for i in range(0,len(b)):
    if b[i]%2 ==0:
        even=even+b[i]
    else:
        odd=odd+b[i]
print(even,odd)

